---
- hosts: jessie
  become: yes
  tasks:
    - name: Instala Ruby
      apt: pkg=ruby-full state=present
    - name: Instala sinatra
      apt: pkg=ruby-sinatra state=present
    - gem:
        name: httparty
        state: latest
